In [2]:
%pip install sympy
import sympy as sp
sp.init_printing(use_unicode=True)
a, b, c = sp.symbols('a b c')

A = sp.Matrix([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
A.det()
A.T
A.inv()
A * b

  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: C:\Users\ADMIN\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


⎡ b   2⋅b  3⋅b⎤
⎢             ⎥
⎢ 0    b   4⋅b⎥
⎢             ⎥
⎣5⋅b  6⋅b   0 ⎦

In [3]:
import numpy as np 
A = np.array([[2, 3], [4, 5]])
B = np.array([[3, 6], [9, 2]])
print(np.linalg.inv(A))
print(np.transpose(A))
print(np.linalg.det(A))
print(A * B)  # element wise
print(A.dot(B))  # matrix multiplication
print(np.dot(A, B))  # matrix multiplication

[[-2.5  1.5]
 [ 2.  -1. ]]
[[2 4]
 [3 5]]
-2.0
[[ 6 18]
 [36 10]]
[[33 18]
 [57 34]]
[[33 18]
 [57 34]]
